Added vid tutorial
dj1ch/minigotchi-ESP32 pull request #25
Opened 2024-06-09 02:09 UTC by ATOMNFT

Added a video tutorial to install readme showing how to make the edits in platform.txt file.

2024-06-10 06:31 UTC, dj1ch commented
lgtm for the most part, the only problem is that the lilygo t display s3 and cyd(I think) repo has it's own way of installing TFT_eSPI, where you grab files from the repo(specifically folders) then move them to your libraries folder. I'm not sure if m5 has a way of doing that. I did find these repos though, not sure if these can make the install process easier.

https://github.com/m5stack/M5Stack/tree/master
https://github.com/m5stack/M5Tough

2024-06-10 06:40 UTC, dj1ch requested changes
Might wanna double check with how we install TFT_eSPI and do the (weird) user setups lol. Everything else good for the most part

2024-06-10 11:11 UTC, ATOMNFT commented
> lgtm for the most part, the only problem is that the lilygo t display s3 and cyd(I think) repo has it's own way of installing TFT_eSPI, where you grab files from the repo(specifically folders) then move them to your libraries folder. I'm not sure if m5 has a way of doing that. I did find these repos though, not sure if these can make the install process easier.
> 
> https://github.com/m5stack/M5Stack/tree/master
> https://github.com/m5stack/M5Tough
> 

I have the user setup files and directions available on the repo. It's the same method for the CYD and t-display. Just move over user setup files and define which board your using. It's fairly simple IMO.

2024-06-10 11:12 UTC, ATOMNFT commented
> Might wanna double check with how we install TFT_eSPI and do the (weird) user setups lol. Everything else good for the most part

Again, the directions and files are in the repo. It's a simple process.

2024-06-10 13:57 UTC, ATOMNFT commented on User_Setup_Files/User_Setup_Files.zip
Addressed.

2024-06-10 19:55 UTC, ATOMNFT commented
> lgtm for the most part, the only problem is that the lilygo t display s3 and cyd(I think) repo has it's own way of installing TFT_eSPI, where you grab files from the repo(specifically folders) then move them to your libraries folder. I'm not sure if m5 has a way of doing that. I did find these repos though, not sure if these can make the install process easier.
> 
> https://github.com/m5stack/M5Stack/tree/master https://github.com/m5stack/M5Tough

You can install the tft_espi lib from inside ardunio or from the github repo. But the lilygo and t-display use the same lib. M5 is the same. M5sticks can  use tft lib or M5stack lib. I'm using the tft lib for m5sticks as it's easier to build/compile in arduino and requires no extra libs to install. Once the user has TFT_eSPI lib installed they can use the User_setup_select file along with the User_setup files for each device to define which device they want to use. Hope this makes sense. If you need more clarification you can read https://github.com/Bodmer/TFT_eSPI.

2024-06-10 22:16 UTC, dj1ch commented
Though the videos and stuff are pretty helpful, if you want I can put them on a youtube channel or something

2024-06-11 13:37 UTC, dj1ch requested changes

2024-06-12 00:23 UTC, dj1ch requested changes

2024-06-12 00:23 UTC, dj1ch commented on User_Setup_Files/README.md
Should probably clarify that I would prefer that I have screen setup in the [INSTALL.md](https://github.com/dj1ch/minigotchi-ESP32/blob/main/INSTALL.md), either have this linked in the install guide or add this as a section, I think another README might make this a bit more confusing for beginners(when it could be easier when everything is added to or linked in inside the INSTALL.md)

2024-06-12 16:35 UTC, ATOMNFT commented on User_Setup_Files/README.md
That's fine. How ever you would like to keep it would be fine. I only added to the readme on my repo as it's forked. Please feel free to adjust, rearrange or anything else you see fit.

2024-06-21 00:26 UTC, closed without merging